module Onigiri
  class Ingredient < Tag
    class << self
      attr_accessor :ingredients

      def scan(tokens)
        tokens.each do |token|
          scan_for_ingredient token
        end
      end

      def scan_for_ingredient(token)
        ingredients.each do |correct_form, variations|
          variations.each do |var|
            if token.name.gsub("_", " ") =~ /\b#{var}\b/
              token.add_tag new(correct_form)
              return
            end
          end
        end
      end

      # Checkes given text for any multi word ingredients and replaces them
      # with the dasherized correct form i.e. cherry tomato => cherry_tomato
      # This prevents such an ingredient being spliced into multiple tokens 
      def normalize(text)
        normalized = text
        ingredients.each do |correct_form, variations|
          variations.each do |v|
            normalized.gsub!(v, correct_form.gsub(" ", "_"))
          end
        end
        normalized
      end

      def set_ingredient(correct_form, *variations)
        @ingredients ||={}
        dasherized_form = correct_form.gsub(" ", "_") #dasherize multiword ingredients to prevent dicing by their spaces into multiple tokens later on.
        @ingredients[correct_form] = variations
        @ingredients[correct_form].push correct_form #and remember to add dasherized_form to variations for use in token scanning later
      end
    end


    set_ingredient 'abalone'
    set_ingredient 'absinthe'
    set_ingredient 'achar'
    set_ingredient 'acidulated water'
    set_ingredient 'ackee'
    set_ingredient 'acorn squash'
    set_ingredient 'adobo'
    set_ingredient 'advieh'
    set_ingredient 'chili pepper'
    set_ingredient 'agar'
    set_ingredient 'aioli'
    set_ingredient 'ajowan'
    set_ingredient 'aleppo pepper'
    set_ingredient 'alfalfa sprout', 'alfalfa sprouts'
    set_ingredient 'alfredo sauce'
    set_ingredient 'alitame'
    set_ingredient 'alize liqueur'
    set_ingredient 'alligator'
    set_ingredient 'allspice'
    set_ingredient 'almond', 'almonds'
    set_ingredient 'almond bark'
    set_ingredient 'almond butter'
    set_ingredient 'almond extract'
    set_ingredient 'almond paste'
    set_ingredient 'alum'
    set_ingredient 'amaranth'
    set_ingredient 'amarena cherry', 'amarena cherries'
    set_ingredient 'amaretti'
    set_ingredient 'amaretto'
    set_ingredient 'amarula cream liqueur'
    set_ingredient 'amchoor powder'
    set_ingredient 'amla'
    set_ingredient 'ammonium bicarbonate'
    set_ingredient 'anchovette'
    set_ingredient 'anchovies'
    set_ingredient 'anchovy paste'
    set_ingredient 'andouille sausage'
    set_ingredient 'angelica'
    set_ingredient 'anise'
    set_ingredient 'annatto seed', 'annatto seed'
    set_ingredient 'apple', 'apples'
    set_ingredient 'apple butter'
    set_ingredient 'applesauce'
    set_ingredient 'apricot', 'apricots'
    set_ingredient 'aquavit'
    set_ingredient 'arak'
    set_ingredient 'arborio rice'
    set_ingredient 'argan oil'
    set_ingredient 'arrowroot'
    set_ingredient 'artichoke', 'arichokes'
    set_ingredient 'artificial sweetener'
    set_ingredient 'arugula'
    set_ingredient 'asadero'
    set_ingredient 'asafetida'
    set_ingredient 'asiago cheese'
    set_ingredient 'asparagus'
    set_ingredient 'aspic'
    set_ingredient 'avocado', 'avocados', 'avocadoes'
    set_ingredient 'azuki bean', 'azuki beans'
    set_ingredient 'baba'
    set_ingredient 'baba ghanoush'
    set_ingredient 'babaco'
    set_ingredient 'babka'
    set_ingredient 'kiwi','kiwis'
    set_ingredient 'baby marrows'
    set_ingredient 'bacon'
    set_ingredient 'bacon grease'
    set_ingredient 'bagel', 'bagels'
    set_ingredient 'bagna cauda'
    set_ingredient 'bagoong'
    set_ingredient 'baguette'
    set_ingredient 'baharat'
    set_ingredient 'bake blind'
    set_ingredient 'baking powder'
    set_ingredient 'baking soda'
    set_ingredient 'baklava'
    set_ingredient 'balmain bug'
    set_ingredient 'balsamic vinegar'
    set_ingredient 'bamboo shoot', 'bamboo shoots'
    set_ingredient 'banana', 'bananas'
    set_ingredient 'bangers'
    set_ingredient 'bannocks'
    set_ingredient 'banon cheese'
    set_ingredient 'barbecue sauce'
    set_ingredient 'barberry', 'barberries'
    set_ingredient 'bard'
    set_ingredient 'barley'
    set_ingredient 'barley sugar'
    set_ingredient 'baron'
    set_ingredient 'basil'
    set_ingredient 'basket cheese'
    set_ingredient 'basmati rice'
    set_ingredient 'bass'
    set_ingredient 'bay leaf', 'bay leaves'
    set_ingredient 'beans'
    set_ingredient 'bean sauce'
    set_ingredient 'bean sprout', 'bean sprouts'
    set_ingredient 'bean thread', 'bean threads'
    set_ingredient 'beat'
    set_ingredient 'bechamel'
    set_ingredient 'beef'
    set_ingredient 'beef round cut', 'beef round cuts'
    set_ingredient 'beer'
    set_ingredient 'beet', 'beets'
    set_ingredient 'bel paese'
    set_ingredient 'berbere'
    set_ingredient 'berries', 'berry'
    set_ingredient 'beurre blanc'
    set_ingredient 'beurre manie'
    set_ingredient 'beurre manie'
    set_ingredient 'biltong'
    set_ingredient 'biscuit mix'
    set_ingredient 'bisque'
    set_ingredient 'bitter melon'
    set_ingredient 'black beans'
    set_ingredient 'black kale'
    set_ingredient 'black olives'
    set_ingredient 'black pepper', 'black-?pepp?er'
    set_ingredient 'blackeyed pea', 'blackeyed peas', 'black eyed pea', 'blackey ed peas'
    set_ingredient 'blackberries'
    set_ingredient 'blanch'
    set_ingredient 'blue cheese'
    set_ingredient 'blueberries'
    set_ingredient 'boerewors'
    set_ingredient 'boil'
    set_ingredient 'bok choy'
    set_ingredient 'bombay duck'
    set_ingredient 'bon appetit seasoning'
    set_ingredient 'borage'
    set_ingredient 'borscht'
    set_ingredient 'bottarga'
    set_ingredient 'bouillon'
    set_ingredient 'bouquet garni'
    set_ingredient 'bourbon'
    set_ingredient 'boursin cheese'
    set_ingredient 'braai'
    set_ingredient 'braise'
    set_ingredient 'brandy'
    set_ingredient 'brazil nuts'
    set_ingredient 'breadcrumbs'
    set_ingredient 'breadfruit'
    set_ingredient 'bresaola'
    set_ingredient 'brewers yeast'
    set_ingredient 'brick cheese'
    set_ingredient 'broccoli'
    set_ingredient 'broccoli raab'
    set_ingredient 'broil'
    set_ingredient 'broth'
    set_ingredient 'brown rice'
    set_ingredient 'brown sugar'
    set_ingredient 'brunoise'
    set_ingredient 'bruschetta'
    set_ingredient 'brussels sprouts'
    set_ingredient 'buckwheat'
    set_ingredient 'buckwheat groats'
    set_ingredient 'buerre manie'
    set_ingredient 'buerre manie'
    set_ingredient 'bulgur wheat'
    set_ingredient 'bundt pan'
    set_ingredient 'butter'
    set_ingredient 'buttermilk'
    set_ingredient 'butternut squash'
    set_ingredient 'cabbage'
    set_ingredient 'cachaca'
    set_ingredient 'cactus'
    set_ingredient 'caerphilly'
    set_ingredient 'calabaza'
    set_ingredient 'callaloo'
    set_ingredient 'calvados'
    set_ingredient 'campden tablets'
    set_ingredient 'canadian bacon'
    set_ingredient 'candy making temperatures'
    set_ingredient 'candy thermometers'
    set_ingredient 'cannellini beans'
    set_ingredient 'canola oil'
    set_ingredient 'cantaloupes'
    set_ingredient 'cape gooseberries'
    set_ingredient 'capers'
    set_ingredient 'cappuccino latte'
    set_ingredient 'capsicums'
    set_ingredient 'carambola'
    set_ingredient 'caramelize'
    set_ingredient 'caraway seeds'
    set_ingredient 'carboy'
    set_ingredient 'cardamom'
    set_ingredient 'carob'
    set_ingredient 'carrageen'
    set_ingredient 'carrot', 'carrots'
    set_ingredient 'cashew nut'
    set_ingredient 'cassava'
    set_ingredient 'casserole'
    set_ingredient 'catfish'
    set_ingredient 'caul'
    set_ingredient 'cauliflower'
    set_ingredient 'caviar'
    set_ingredient 'cayenne pepper'
    set_ingredient 'celeriac'
    set_ingredient 'celery'
    set_ingredient 'celery seeds'
    set_ingredient 'chai'
    set_ingredient 'chambord'
    set_ingredient 'champagne yeast'
    set_ingredient 'chard'
    set_ingredient 'chaurice sausage'
    set_ingredient 'chayote'
    set_ingredient 'cheddar cheese'
    set_ingredient 'cheese'
    set_ingredient 'cheesecloth'
    set_ingredient 'chendol'
    set_ingredient 'cherimoya'
    set_ingredient 'cherries'
    set_ingredient 'chervil'
    set_ingredient 'cheshire cheese'
    set_ingredient 'chestnuts'
    set_ingredient 'chicken', 'chickens'
    set_ingredient 'chicken livers'
    set_ingredient 'chickpeas'
    set_ingredient 'chicory'
    set_ingredient 'chiffonade'
    set_ingredient 'chile peppers'
    set_ingredient 'chili powder'
    set_ingredient 'chili sauce'
    set_ingredient 'chinese cabbage'
    set_ingredient 'chinese dates'
    set_ingredient 'chipotle peppers'
    set_ingredient 'chives'
    set_ingredient 'chocolate'
    set_ingredient 'chowder'
    set_ingredient 'chutney'
    set_ingredient 'cider'
    set_ingredient 'cider vinegar'
    set_ingredient 'cilantro'
    set_ingredient 'cinnamon'
    set_ingredient 'citron'
    set_ingredient 'citrus oils'
    set_ingredient 'clafouti'
    set_ingredient 'clams'
    set_ingredient 'clarified butter'
    set_ingredient 'clarify'
    set_ingredient 'cloves'
    set_ingredient 'cocoa powder'
    set_ingredient 'coconuts'
    set_ingredient 'coconut milk or cream'
    set_ingredient 'coconut oil'
    set_ingredient 'cod'
    set_ingredient 'coffee'
    set_ingredient 'colby'
    set_ingredient 'common container sizes'
    set_ingredient 'confit'
    set_ingredient 'cookies'
    set_ingredient 'cool whip'
    set_ingredient 'copha'
    set_ingredient 'coriander'
    set_ingredient 'corn'
    set_ingredient 'corn flour'
    set_ingredient 'corn syrup'
    set_ingredient 'corned beef'
    set_ingredient 'cornichons'
    set_ingredient 'cornish yarg cheese'
    set_ingredient 'cornmeal'
    set_ingredient 'cornstarch'
    set_ingredient 'cottage cheese'
    set_ingredient 'cottage roll'
    set_ingredient 'coulis'
    set_ingredient 'couscous'
    set_ingredient 'crabs'
    set_ingredient 'craisins'
    set_ingredient 'cranberries'
    set_ingredient 'cranberry bean'
    set_ingredient 'crayfish'
    set_ingredient 'cream cheese'
    set_ingredient 'cream of coconut'
    set_ingredient 'cream of tartar'
    set_ingredient 'cream of wheat'
    set_ingredient 'cream, to'
    set_ingredient 'crema de leche'
    set_ingredient 'creme brulee'
    set_ingredient 'creme de cacao'
    set_ingredient 'creme de cassis'
    set_ingredient 'creme de menthe'
    set_ingredient 'creme fraiche'
    set_ingredient 'cremini mushrooms'
    set_ingredient 'creole sausage'
    set_ingredient 'crock pot'
    set_ingredient 'crostini'
    set_ingredient 'croutons'
    set_ingredient 'crozzled'
    set_ingredient 'crystallized ginger'
    set_ingredient 'cucumbers'
    set_ingredient 'cucuzza'
    set_ingredient 'cumin'
    set_ingredient 'curacao'
    set_ingredient 'currants'
    set_ingredient 'curry leaves'
    set_ingredient 'curry paste'
    set_ingredient 'curry powder'
    set_ingredient 'custard'
    set_ingredient 'dash'
    set_ingredient 'dates'
    set_ingredient 'date sugar'
    set_ingredient 'deglaze'
    set_ingredient 'demi-glace'
    set_ingredient 'derby cheese'
    set_ingredient 'desiccated'
    set_ingredient 'desserts'
    set_ingredient 'dhania-jeera powder'
    set_ingredient 'dice'
    set_ingredient 'dill'
    set_ingredient 'dovedale cheese'
    set_ingredient 'dragees'
    set_ingredient 'dredge'
    set_ingredient 'dried leeks'
    set_ingredient 'dripping'
    set_ingredient 'duck'
    set_ingredient 'dumpling'
    set_ingredient 'durian'
    set_ingredient 'dutch oven'
    set_ingredient 'eau de vie'
    set_ingredient 'eclairs'
    set_ingredient 'edam'
    set_ingredient 'edamame'
    set_ingredient 'eels'
    set_ingredient 'egg', 'eggs?'
    set_ingredient 'egg substitutes'
    set_ingredient 'eggplants'
    set_ingredient 'elderberries'
    set_ingredient 'endive'
    set_ingredient 'english muffins'
    set_ingredient 'english mustard'
    set_ingredient 'epazote'
    set_ingredient 'erythritol'
    set_ingredient 'escalopes'
    set_ingredient 'falafel'
    set_ingredient 'falernum'
    set_ingredient 'farina'
    set_ingredient 'farmer cheese'
    set_ingredient 'fava beans'
    set_ingredient 'feet'
    set_ingredient 'feijoa'
    set_ingredient 'fennel'
    set_ingredient 'fennel seeds'
    set_ingredient 'fenugreek'
    set_ingredient 'fermented black beans'
    set_ingredient 'feta cheese'
    set_ingredient 'figs'
    set_ingredient 'file powder'
    set_ingredient 'finnan haddie'
    set_ingredient 'firm-ball stage'
    set_ingredient 'fish sauce'
    set_ingredient 'fish slice'
    set_ingredient 'five-spice powder'
    set_ingredient 'flageolet'
    set_ingredient 'flax seed'
    set_ingredient 'flounder'
    set_ingredient 'flour'
    set_ingredient 'focaccia'
    set_ingredient 'foie gras'
    set_ingredient 'fold'
    set_ingredient 'fond'
    set_ingredient 'fontina cheese'
    set_ingredient 'forcemeat'
    set_ingredient 'frangipane'
    set_ingredient 'french fries'
    set_ingredient 'french-style green beans'
    set_ingredient 'fried rice seasoning'
    set_ingredient 'frisee'
    set_ingredient 'fructose'
    set_ingredient 'frying pan'
    set_ingredient 'galangal'
    set_ingredient 'ganache'
    set_ingredient 'garlic'
    set_ingredient 'garlic powder'
    set_ingredient 'gelatin'
    set_ingredient 'gelatinized starch'
    set_ingredient 'ghee'
    set_ingredient 'ginger'
    set_ingredient 'ginger ale'
    set_ingredient 'ginger beer'
    set_ingredient 'ginger syrup'
    set_ingredient 'ginkgo nut'
    set_ingredient 'glace de viande'
    set_ingredient 'gloucester'
    set_ingredient 'gluten'
    set_ingredient 'gluten-free brand names'
    set_ingredient 'goji berry'
    set_ingredient 'golden syrup'
    set_ingredient 'geese'
    set_ingredient 'gooseberries'
    set_ingredient 'gorgonzola'
    set_ingredient 'gouda'
    set_ingredient 'graham crackers'
    set_ingredient 'grains of paradise'
    set_ingredient 'gram flour'
    set_ingredient 'grand marnier'
    set_ingredient 'granola'
    set_ingredient 'grapes'
    set_ingredient 'grapefruits'
    set_ingredient 'grating cheese'
    set_ingredient 'great northern beans'
    set_ingredient 'green beans'
    set_ingredient 'green kern'
    set_ingredient 'green onions'
    set_ingredient 'greens'
    set_ingredient 'grits'
    set_ingredient 'grouper'
    set_ingredient 'gruyere'
    set_ingredient 'guanbana'
    set_ingredient 'guavas'
    set_ingredient 'gumbo'
    set_ingredient 'habanero chilies'
    set_ingredient 'haddock'
    set_ingredient 'half-and-half'
    set_ingredient 'halibut'
    set_ingredient 'ham'
    set_ingredient 'ham hock'
    set_ingredient 'hamburger'
    set_ingredient 'hard cheese'
    set_ingredient 'harissa'
    set_ingredient 'hash browns'
    set_ingredient 'havarti'
    set_ingredient 'hawaij'
    set_ingredient 'hazelnuts'
    set_ingredient 'hearts of palm'
    set_ingredient 'heavy cream'
    set_ingredient 'heirloom weights & measurements'
    set_ingredient 'herbs'
    set_ingredient 'herbsaint'
    set_ingredient 'herring'
    set_ingredient 'high altitude adjustment for cookies'
    set_ingredient 'high altitude adjustment for deep fat frying'
    set_ingredient 'high altitude baking quick breads'
    set_ingredient 'hispanic cheese'
    set_ingredient 'hoisin sauce'
    set_ingredient 'hoja santa'
    set_ingredient 'hoki'
    set_ingredient 'hominy'
    set_ingredient 'honey'
    set_ingredient 'honeydew melons'
    set_ingredient 'horseradish'
    set_ingredient 'hot sauce'
    set_ingredient 'huckleberries'
    set_ingredient 'hundred-year eggs'
    set_ingredient 'hungarian wax chile'
    set_ingredient 'hyssop'
    set_ingredient 'ice cream'
    set_ingredient 'ice wine'
    set_ingredient 'icing sugar'
    set_ingredient 'indian pudding'
    set_ingredient 'infusion'
    set_ingredient 'insalata'
    set_ingredient 'instant espresso'
    set_ingredient 'instant potato flakes'
    set_ingredient 'invert sugar'
    set_ingredient 'irish coffee'
    set_ingredient 'irish cream liqueur'
    set_ingredient 'irish mist'
    set_ingredient 'isinglass'
    set_ingredient 'jack cheese'
    set_ingredient 'jaggery'
    set_ingredient 'jambalaya'
    set_ingredient 'jamon serrano'
    set_ingredient 'jamun'
    set_ingredient 'jelly beans'
    set_ingredient 'jelly roll'
    set_ingredient 'jelly tots'
    set_ingredient 'jerusalem artichokes'
    set_ingredient 'jicama'
    set_ingredient 'joint'
    set_ingredient 'jowl'
    set_ingredient 'kabsa spice mix'
    set_ingredient 'kaffir lime'
    set_ingredient 'kahlua'
    set_ingredient 'kalamata olives'
    set_ingredient 'kale'
    set_ingredient 'kamaboko'
    set_ingredient 'kasha'
    set_ingredient 'kashk'
    set_ingredient 'ketchup'
    set_ingredient 'ketjap manis'
    set_ingredient 'kewra essence'
    set_ingredient 'kewra water'
    set_ingredient 'khus essence'
    set_ingredient 'kidney beans'
    set_ingredient 'kielbasa'
    set_ingredient 'kirsch'
    set_ingredient 'kitchen bouquet'
    set_ingredient 'kiwi fruit'
    set_ingredient 'kohlrabi'
    set_ingredient 'konfyt'
    set_ingredient 'kosher'
    set_ingredient 'kudzu'
    set_ingredient 'kugel'
    set_ingredient 'kumquats'
    set_ingredient 'lactose-free brand names'
    set_ingredient 'ladyfingers'
    set_ingredient 'lamb'
    set_ingredient 'lambsquarters'
    set_ingredient 'lampreys'
    set_ingredient 'lancashire cheese'
    set_ingredient 'lardons'
    set_ingredient 'lavender'
    set_ingredient 'lecithin'
    set_ingredient 'leeks'
    set_ingredient 'lefse'
    set_ingredient 'lemons'
    set_ingredient 'lemon balm'
    set_ingredient 'lemon grass'
    set_ingredient 'lemon juice'
    set_ingredient 'lemon peel'
    set_ingredient 'lentils'
    set_ingredient 'lettuce'
    set_ingredient 'liaison'
    set_ingredient 'light cream'
    set_ingredient 'lima beans'
    set_ingredient 'limes'
    set_ingredient 'lingcod'
    set_ingredient 'litchi'
    set_ingredient 'liver'
    set_ingredient 'lobsters'
    set_ingredient 'longans'
    set_ingredient 'loquat'
    set_ingredient 'lotus'
    set_ingredient 'lovage'
    set_ingredient 'lumpia wrappers'
    set_ingredient 'macaroni'
    set_ingredient 'mace'
    set_ingredient 'mackerel'
    set_ingredient 'madeira'
    set_ingredient 'mahi mahi'
    set_ingredient 'mahleb'
    set_ingredient 'malt vinegar'
    set_ingredient 'malta'
    set_ingredient 'mandarin oranges'
    set_ingredient 'mange-tout'
    set_ingredient 'mangoes'
    set_ingredient 'mangosteen'
    set_ingredient 'manzanilla olives'
    set_ingredient 'maple syrup'
    set_ingredient 'maraschino cherries'
    set_ingredient 'margarine'
    set_ingredient 'marjoram'
    set_ingredient 'marmalade'
    set_ingredient 'marsala'
    set_ingredient 'marshmallows'
    set_ingredient 'marula'
    set_ingredient 'marzipan'
    set_ingredient 'masa harina'
    set_ingredient 'masala'
    set_ingredient 'mascarpone'
    set_ingredient 'matignon'
    set_ingredient 'matzo meal'
    set_ingredient 'mayonnaise'
    set_ingredient 'melons'
    set_ingredient 'meringue powder'
    set_ingredient 'mesclun'
    set_ingredient 'mettwursts'
    set_ingredient 'milk'
    set_ingredient 'mimolette cheese'
    set_ingredient 'mince'
    set_ingredient 'mint'
    set_ingredient 'miracle whip dressing'
    set_ingredient 'mirepoix'
    set_ingredient 'miso'
    set_ingredient 'mixed spice'
    set_ingredient 'mizuna'
    set_ingredient 'moambe sauce'
    set_ingredient 'molasses'
    set_ingredient 'monkfish'
    set_ingredient 'monosodium glutamate'
    set_ingredient 'moo shu wrappers'
    set_ingredient 'morels'
    set_ingredient 'moreton bay bug'
    set_ingredient 'mortadella'
    set_ingredient 'mostaccioli'
    set_ingredient 'mozzarella'
    set_ingredient "mrs dash's fiesta lime salt-free seasoning"
    set_ingredient 'muddle'
    set_ingredient 'mugwort'
    set_ingredient 'mung beans'
    set_ingredient 'muscadine grape'
    set_ingredient 'muscovado sugar'
    set_ingredient 'muscovy duck'
    set_ingredient 'mushrooms'
    set_ingredient 'muskmelons'
    set_ingredient 'mussels'
    set_ingredient 'mustard, prepared'
    set_ingredient 'nasturtium'
    set_ingredient 'navy beans'
    set_ingredient 'nectarines'
    set_ingredient 'nigella seeds'
    set_ingredient 'nopales'
    set_ingredient 'nori'
    set_ingredient "o'brien potatoes"
    set_ingredient 'oamc'
    set_ingredient 'oatmeal'
    set_ingredient 'octopus'
    set_ingredient 'offal'
    set_ingredient 'okra'
    set_ingredient 'olives'
    set_ingredient 'olive oil'
    set_ingredient 'onion', 'onions?'
    set_ingredient 'onion powder'
    set_ingredient 'oranges'
    set_ingredient 'orange flower water'
    set_ingredient 'orange peel'
    set_ingredient 'oregano'
    set_ingredient 'orgeat syrup'
    set_ingredient 'oven temperatures'
    set_ingredient 'oyster sauce'
    set_ingredient 'palm oil'
    set_ingredient 'palm sugar'
    set_ingredient 'pancetta'
    set_ingredient 'panir'
    set_ingredient 'panko'
    set_ingredient 'panna cotta'
    set_ingredient 'papayas'
    set_ingredient 'paprika'
    set_ingredient 'parboil'
    set_ingredient 'parchment paper'
    set_ingredient 'parmesan'
    set_ingredient 'parsley'
    set_ingredient 'parsnips'
    set_ingredient 'passion fruit'
    set_ingredient 'pasta'
    set_ingredient 'pasta filata cheese'
    set_ingredient 'pastis'
    set_ingredient 'paysanne'
    set_ingredient 'peas'
    set_ingredient 'pea beans'
    set_ingredient 'peaches'
    set_ingredient 'peanuts'
    set_ingredient 'peanut butter'
    set_ingredient 'pears'
    set_ingredient 'pecans'
    set_ingredient 'pelargonium citronellum'
    set_ingredient 'peppadew peppers'
    set_ingredient 'pepper'
    set_ingredient 'perch'
    set_ingredient 'periwinkles'
    set_ingredient 'persimmons'
    set_ingredient 'pesto'
    set_ingredient 'pheasants'
    set_ingredient 'phyllo dough'
    set_ingredient 'pickles'
    set_ingredient 'pickling lime'
    set_ingredient 'pico de gallo'
    set_ingredient 'pie melon'
    set_ingredient 'pie servers'
    set_ingredient 'pierogies'
    set_ingredient "pig's cheek"
    set_ingredient "pig's feet"
    set_ingredient 'pike'
    set_ingredient 'piloncillo'
    set_ingredient 'pimiento'
    set_ingredient 'pinch'
    set_ingredient 'pine nuts'
    set_ingredient 'pineapples'
    set_ingredient 'pink beans'
    set_ingredient 'pinto beans'
    set_ingredient 'pistachios'
    set_ingredient 'plantains'
    set_ingredient 'plastic wrap'
    set_ingredient 'plums'
    set_ingredient 'plum tomatoes'
    set_ingredient 'plumcots'
    set_ingredient 'poach'
    set_ingredient 'polenta'
    set_ingredient 'pomegranates'
    set_ingredient 'pomegranate molasses'
    set_ingredient 'pomelos'
    set_ingredient 'pompano'
    set_ingredient 'ponzu'
    set_ingredient 'poppy seeds'
    set_ingredient 'porcini'
    set_ingredient 'pork'
    set_ingredient 'portabellas'
    set_ingredient 'potatoes'
    set_ingredient 'potato chips'
    set_ingredient 'potato starch'
    set_ingredient 'poultry seasoning'
    set_ingredient 'poussin'
    set_ingredient 'powdered sugar'
    set_ingredient 'prawns'
    set_ingredient 'preheat'
    set_ingredient 'preserves'
    set_ingredient 'preserved lemon'
    set_ingredient 'processed cheese'
    set_ingredient 'proof'
    set_ingredient 'prosciuttini'
    set_ingredient 'prosciutto'
    set_ingredient 'provolone'
    set_ingredient 'prunes'
    set_ingredient 'pudding mixes'
    set_ingredient 'puff pastries'
    set_ingredient 'pulses'
    set_ingredient 'pumpkins'
    set_ingredient 'pumpkin pie spice'
    set_ingredient 'pumpkin seeds'
    set_ingredient 'quail'
    set_ingredient 'quark'
    set_ingredient 'quenelles'
    set_ingredient 'quesadilla'
    set_ingredient 'queso'
    set_ingredient 'quetsch'
    set_ingredient 'quince'
    set_ingredient 'quinoa'
    set_ingredient 'quorn'
    set_ingredient 'rabbits'
    set_ingredient 'radiatore'
    set_ingredient 'radicchio'
    set_ingredient 'radishes'
    set_ingredient 'raisins'
    set_ingredient 'rambutan'
    set_ingredient 'ramps'
    set_ingredient 'ras el hanout'
    set_ingredient 'raspberries'
    set_ingredient 'raw sugar'
    set_ingredient 'recaito'
    set_ingredient 'red beans'
    set_ingredient 'red cabbage'
    set_ingredient 'red chile powder'
    set_ingredient 'red leicester'
    set_ingredient 'red pepper flakes'
    set_ingredient 'red snapper'
    set_ingredient 'remoulade'
    set_ingredient 'rhubarb'
    set_ingredient 'rice'
    set_ingredient 'rice paddy herb'
    set_ingredient 'rice paper'
    set_ingredient 'rice sticks'
    set_ingredient 'rice vermicelli'
    set_ingredient 'rice vinegar'
    set_ingredient 'rice wines'
    set_ingredient 'ricotta cheese'
    set_ingredient 'romaine lettuce'
    set_ingredient 'romano cheese'
    set_ingredient 'rookworst'
    set_ingredient 'rose essense'
    set_ingredient 'rose water'
    set_ingredient 'rosemary'
    set_ingredient 'rotel tomatoes'
    set_ingredient 'rotisserie'
    set_ingredient 'roux'
    set_ingredient 'rum'
    set_ingredient 'rusks'
    set_ingredient 'rutabagas'
    set_ingredient 'saffron'
    set_ingredient 'sage'
    set_ingredient 'sago'
    set_ingredient 'salmon'
    set_ingredient 'salsa'
    set_ingredient 'salsify'
    set_ingredient 'salt'
    set_ingredient 'salt pork'
    set_ingredient 'sambal'
    set_ingredient 'sand dab'
    set_ingredient 'sandwich'
    set_ingredient 'sardines'
    set_ingredient 'satay'
    set_ingredient 'sauerkraut'
    set_ingredient 'saunf'
    set_ingredient 'sausages'
    set_ingredient 'saute'
    set_ingredient 'savory'
    set_ingredient 'sazon'
    set_ingredient 'scald'
    set_ingredient 'scallops'
    set_ingredient 'scaloppine'
    set_ingredient 'scotch bonnet chiles'
    set_ingredient 'scoville chart'
    set_ingredient 'scrapple'
    set_ingredient 'screwpine leaves'
    set_ingredient 'sea cucumbers'
    set_ingredient 'sear'
    set_ingredient 'seed'
    set_ingredient 'seitan'
    set_ingredient 'semi-hard cheese'
    set_ingredient 'semisweet chocolate'
    set_ingredient 'semolina'
    set_ingredient 'sesame seeds'
    set_ingredient 'seville orange'
    set_ingredient 'shallots'
    set_ingredient 'sherry'
    set_ingredient 'shitakes'
    set_ingredient 'shortening'
    set_ingredient 'shrimp'
    set_ingredient 'shrimp paste'
    set_ingredient 'shropshire blue'
    set_ingredient 'simmer'
    set_ingredient 'slipper lobster'
    set_ingredient 'smelt'
    set_ingredient 'smoke seasoning'
    set_ingredient 'smoked salmon'
    set_ingredient 'snap peas'
    set_ingredient 'snapper'
    set_ingredient 'snoek'
    set_ingredient 'snow peas'
    set_ingredient 'soba'
    set_ingredient 'soba tsuyu'
    set_ingredient 'soda crackers'
    set_ingredient 'soft cheese'
    set_ingredient 'soft-shell crabs'
    set_ingredient 'sole'
    set_ingredient 'somen'
    set_ingredient 'sorghum'
    set_ingredient 'sorrel'
    set_ingredient 'souffle'
    set_ingredient 'sour cream'
    set_ingredient 'soy sauce'
    set_ingredient 'soybeans'
    set_ingredient 'soymilk'
    set_ingredient 'spaetzle'
    set_ingredient 'spaghetti'
    set_ingredient 'spanish cheeses'
    set_ingredient 'spatchcock'
    set_ingredient 'spearmint'
    set_ingredient 'specialty cheeses'
    set_ingredient 'spinach'
    set_ingredient 'split peas'
    set_ingredient 'squash'
    set_ingredient 'squid'
    set_ingredient 'star anise'
    set_ingredient 'steaks'
    set_ingredient 'steam'
    set_ingredient 'stevia'
    set_ingredient 'stilton'
    set_ingredient 'strawberries'
    set_ingredient 'stuffings'
    set_ingredient 'sturgeon'
    set_ingredient 'sucanat'
    set_ingredient 'succotash'
    set_ingredient 'suet'
    set_ingredient 'sugar'
    set_ingredient 'sultana'
    set_ingredient 'sumac'
    set_ingredient 'summer squash'
    set_ingredient 'sunflower seeds'
    set_ingredient 'sushi'
    set_ingredient 'sweet peppers'
    set_ingredient 'sweet potatoes'
    set_ingredient 'sweetbreads'
    set_ingredient 'sweetened condensed milk'
    set_ingredient 'swiss cheese'
    set_ingredient 'swordfish'
    set_ingredient 'szechuan peppercorn'
    set_ingredient 'tabasco sauce'
    set_ingredient 'tagine'
    set_ingredient 'tahini'
    set_ingredient 'tamarillo'
    set_ingredient 'tamarind'
    set_ingredient 'tandoori paste'
    set_ingredient 'tapioca'
    set_ingredient 'tarragon'
    set_ingredient 'tartar sauce'
    set_ingredient 'tasso'
    set_ingredient 'tatsoi'
    set_ingredient 'tea'
    set_ingredient 'teff'
    set_ingredient 'tempeh'
    set_ingredient 'terrapins'
    set_ingredient 'thyme'
    set_ingredient 'tofu'
    set_ingredient 'togarashi'
    set_ingredient 'tomatoes'
    set_ingredient 'tomato juice'
    set_ingredient 'tomato paste'
    set_ingredient 'tomato puree'
    set_ingredient 'tomato sauce'
    set_ingredient 'tonic water'
    set_ingredient 'tortillas'
    set_ingredient 'trappist or monastery-style cheese'
    set_ingredient 'tripe'
    set_ingredient 'trompette de la mort mushroom'
    set_ingredient 'trout'
    set_ingredient 'truffles'
    set_ingredient 'tuna'
    set_ingredient 'turbinado sugar'
    set_ingredient 'turkeys'
    set_ingredient 'turmeric'
    set_ingredient 'turnips'
    set_ingredient 'turtles'
    set_ingredient 'udo'
    set_ingredient 'udon noodles'
    set_ingredient 'ugli fruit'
    set_ingredient 'umeboshi'
    set_ingredient 'unsweetened chocolate'
    set_ingredient 'urad dal'
    set_ingredient 'vanilla'
    set_ingredient 'vanilla bean'
    set_ingredient 'veal'
    set_ingredient 'vegan brand names'
    set_ingredient 'vegemite'
    set_ingredient 'vegetable marrow'
    set_ingredient 'vegetarian brand names'
    set_ingredient 'veloute'
    set_ingredient 'velveeta'
    set_ingredient 'venison'
    set_ingredient 'vermouth'
    set_ingredient 'vidalia onions'
    set_ingredient 'vincotto'
    set_ingredient 'vinegar'
    set_ingredient 'vital wheat gluten'
    set_ingredient 'wakame seaweed salad'
    set_ingredient 'walnuts'
    set_ingredient 'wasabi'
    set_ingredient 'washed-rind cheese'
    set_ingredient 'water'
    set_ingredient 'water bath'
    set_ingredient 'water chestnuts'
    set_ingredient 'waterblommetji'
    set_ingredient 'watercress'
    set_ingredient 'watermelons'
    set_ingredient 'watermelon radishes'
    set_ingredient 'wattleseed'
    set_ingredient 'weetabix'
    set_ingredient 'weisswurst'
    set_ingredient 'welsh rarebit'
    set_ingredient 'wensleydale cheese'
    set_ingredient 'wheat berries'
    set_ingredient 'wheat germ'
    set_ingredient 'whelks'
    set_ingredient 'white beans'
    set_ingredient 'white chocolate'
    set_ingredient 'wild rice'
    set_ingredient 'wine'
    set_ingredient 'wine vinegar'
    set_ingredient 'won ton skins'
    set_ingredient 'woodruff'
    set_ingredient 'worcestershire sauce'
    set_ingredient 'yabbies'
    set_ingredient 'yeast'
    set_ingredient 'yogurt'
    set_ingredient "za'atar"
    set_ingredient 'zabaglione'
    set_ingredient 'zest'
    set_ingredient 'zinfandel wine'
    set_ingredient 'zucchinis'
  end
end